version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directories:
      - /
      - /pgx
      - /sqlx
      - /tests
    schedule:
      interval: weekly
    allow:
      - dependency-type: all
