version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      all-actions:
        patterns:
          - '*'

  - package-ecosystem: gomod
    directories:
      - /
      - /pgx
      - /sqlx
      - /tests
    schedule:
      interval: weekly
    allow:
      - dependency-type: all
    groups:
      all-gomod:
        patterns:
          - '*'
