linters:
  presets:
    - bugs
    - comment
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - test
    - unused

  enable:
    - misspell

  disable:
    - err113 # forces to use static errors everywhere
    - depguard # forces to manually allow each import
    - exhaustruct # forces to initialize all struct fields
    - tparallel # forces to use parallel tests which is not always possible

issues:
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - wrapcheck

linters-settings:
  paralleltest:
    ignore-missing-subtests: true

run:
  timeout: 1m
