version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - contextcheck
    - copyloopvar
    - dupword
    - errname
    - errorlint
    - fatcontext
    - forcetypeassert
    - gochecknoglobals
    - gochecknoinits
    - gocritic
    - gosec
    - makezero
    - misspell
    - paralleltest
    - prealloc
    - revive
    - rowserrcheck
    - sqlclosecheck
    - unparam
    - wrapcheck
  settings:
    paralleltest:
      ignore-missing-subtests: true
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - wrapcheck
        path: (.+)_test.go
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
